About Page Image styling and Juice
HermanMartinus/justsketchme-frontend pull request #4
Opened 2019-07-05 18:15 UTC by skgarvie

- about images link to custom websites
- flip about images

2019-07-05 19:11 UTC, HermanMartinus requested changes

2019-07-05 19:11 UTC, HermanMartinus commented on _sass/staff.scss
> +	.flip {
`.flip` is repeated?

2019-07-06 06:24 UTC, skgarvie commented
Kind of. The repeated flip is to handle the animation selections

Can prob combine a few of them, but was too complicated for a tired simon.

Will look at again this afternoon

On Fri, Jul 5, 2019, 21:11 Herman <notifications@github.com> wrote:

> *@HermanMartinus* requested changes on this pull request.
> ------------------------------
>
> In _sass/staff.scss
> <https://github.com/HermanMartinus/justsketchme-frontend/pull/4#discussion_r300776189>
> :
>
> > @@ -22,11 +23,79 @@
>  	.square-image {
>  		width: 200px;
>  		height: 200px;
> -			img {
> -				border-radius: 200px;
> +
> +		img {
> +			width:100%;
> +			height:auto;
> +			border-radius: 200px;
> +		}
> +	}
> +
> +	// base
> +	.flip {
>
> .flip is repeated?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HermanMartinus/justsketchme-frontend/pull/4?email_source=notifications&email_token=AB364OGRPWZKQPI6SI6ZSSDP56MGNA5CNFSM4H6NE6A2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5UMG2Y#pullrequestreview-258524011>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB364OE7YDR2GKLAG7Y4W6TP56MGNANCNFSM4H6NE6AQ>
> .
>

2019-07-06 06:58 UTC, HermanMartinus approved these changes

2019-07-06 06:58 UTC, merged

2019-07-06 07:01 UTC, HermanMartinus commented
Noice. Tested on prod and it looks fly